"""Pre-computed geometric bridge artifacts for the intent parser.

Files in this directory are generated by scripts/build_semantic_bridge.py
at build time and ship with the wheel. They are NOT generated at runtime.

- semantic_bridge.npz: numpy compressed archive containing:
    face_sim: (vocab_size, 12) discriminative face similarity
    axis_proj: (vocab_size, 24) pre-normalized axis projections [0,1]
    idf: (vocab_size,) IDF-like weights from frequency rank
    faces: (12,) face names in column order
- semantic_vocab.json: word -> row index mapping for the arrays
"""
