"""Pre-computed semantic artifacts for the intent parser.

Files in this directory are generated by scripts/build_semantic_bridge.py
at build time and ship with the wheel. They are NOT generated at runtime.

- semantic_bridge.npz: numpy compressed array (vocab_size, 12) of word-to-face
  cosine similarities
- semantic_vocab.json: word -> row index mapping for the similarity matrix
"""
